server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/ssm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: hn123456Aa

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hunau.entity  # 注意：对应实体类的路
